[programs.localnet]
solana_app_starter = "5nXr4R26iKVCDvxxLDMxakUpWixDVqgZZhG9pmGXgRvb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
